### PR TITLE
fixes #12 - support for heroku-20 stack

### LINKED ISSUE #12: new support heroku-20
I tried to upgrade Heroku-20, but Graphviz doesn't support this, it's failed.

### PR DESCRIPTION
**Pull request by syphar**
Following the (very good !) notes about adding new stacks and testing, I did the changes needed for supporting the new `heroku-20` stack. 

After the changes I tested all 3 stacks using the docker image. 

I'm happy do improve / change where needed, bash-script is not my best programming language :)

### CODE REVIEW

**Comment by syphar** [comment]
our own Heroku app using this fixed fork also works

**Comment by syphar** [comment]
just thought if we actually should remove the `heroku-16` stack, 
but [in the documentation](https://devcenter.heroku.com/articles/heroku-16-stack) we see that it reaches end-of-life May 2021

**Comment by abutterf** [comment]
Is this going to get merged soon?

**Comment by abutterf** [comment]
\o/ Thank you!

**Comment by weibeld** [comment]
Hi @syphar, thanks for the good work and thorough pull request!

For the `heroku-16` stack, I think it's fine if it gets removed from the buildpack around the official end-of-life in May this year.

**Pull request merged**
